export const ActionTypeTask = {
    CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAILURE: 'CREATE_TASK_FAILURE',
    GET_ALL_TASK_REQUEST: 'GET_ALL_TASK_REQUEST',
    GET_ALL_TASK_SUCCESS: 'GET_ALL_TASK_SUCCESS',
    GET_ALL_TASK_FAILURE: 'GET_ALL_TASK_FAILURE',
}