export const ActionTypes = {
    GET_TODOS: 'GET_TODOS',
    GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
    GET_TODO_FAILURE : 'GET_TODO_FAILURE',
    CREATE_TODO: 'CREATE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    FILTER_DONE: 'FILTER_DONE',
}