export const ActionTypeHome = {
    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILURE: 'GET_ALL_USER_FAILURE',
    GET_MY_INFO_REQUEST: 'GET_MY_INFO_REQUEST',
    GET_MY_INFO_SUCCESS: 'GET_MY_INFO_SUCCESS',
    GET_MY_INFO_FAILURE: 'GET_MY_INFO_FAILURE',
}